config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users,:controllers => { :registrations =>'registrations',:sessions =>'sessions',:passwords =>'passwords' }
  
  
  root :to =>'home#index'
  
  post "home/index", :to => "home#display"
  get "home/display", :to => "home#data_input_of_rest_id", :as => :show_foodcategory
  post "home/data_input_of_rest_id", :to => "home#foodcategories"
  get "home/foodcategories", :to => "home#fooditems", :as => :show_fooditem
  
  
 
end

app/models/foodcategory.rb
class Foodcategory < ActiveRecord::Base
end

app/models/fooditem.rb
class Fooditem < ActiveRecord::Base
end

app/models/restaurantlist.rb
class Restaurantlist < ActiveRecord::Base
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
         
         
   before_save :access_token
   private
   def access_token
     self.useraccesstoken = SecureRandom.uuid
   end
   
   
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_flash_types :error,:another_custom_type
  protect_from_forgery with: :exception
 before_action :authenticate_user!
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def display
    @allresults=Restaurantlist.within(1000, :origin => [params[:lat],params[:lng] ])
   
   # render json: {'here' => allresults} and return
   # render :json => JSON.pretty_generate({'list' => (@allresults.to_a.map(&:serializable_hash))})
  end
   
   def foodcategories
       
    # @count = Restaurantlist.count()
  #@user=Foodcategory.find_by_rest_id(params[:rest_id]) 
  @user = Foodcategory.where("rest_id = ?",params[:rest_id] )
  #if !@user.blank?
  #render json: {'here' => @user } and return 
  #end
 end
 
 def fooditems
   
 end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
     helper :application
   # default from: "salma@clicklabs.in"
  # POST /resource/password
 def new 
 
 end
 
 def create 
   
     @user=User.find_by_email(params[:email])
     if @user
     #@user.send_password_reset 
     Mailer.reset_password_instructions(@user).deliver 
     redirect_to root_path
     else
     flash[:notice] = "email not found"
     render "new"
     
   end
 end
 
 
  def edit
  
  end
  
  
  
  def update
     # @user = current_user
   @user = User.find_by_useraccesstoken(params[:reset_password_token])
     #render json: {'here'=>@user} and return
      
      if @user.update_attribute(:password,params[:password])    # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to root_path
     end
      
      #else
     # render "edit"
   #end
  end



  
  
  
 
 
     
     
 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 def new 
   @user = User.new
 end


def create 
  @user = User.new(user_params)
  #render json: {'here'=>@user} and return
   if @user.save
    #render json: {'here'=>@user} and return
    sign_in @user
    
  else 
    render"new"
    
  
  end
  
  redirect_to root_url

  
 
  
  
  
end


private
 def user_params
params.require(:user).permit(:email, :username, :password, :devicetype,:devicetoken)
end


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
  
  def new 

  end
  
  
  def create
    #  @user = User.new
    # if !@user.blank?
   if (params[:logintype].blank? || params[:devicetype].blank?)
     flash[:error] = "fill all entries"
     render "new"
   end
    if params[:logintype] == "1"
      if @user=User.find_by_email(params[:email])
        if @user.valid_password?(params[:password])
         @user.update_attribute(:devicetype,params[:devicetype])
         @user.update_attribute(:devicetoken,params[:devicetoken])
   # render json: {'here'=>@user}
          sign_in @user
          redirect_to root_path
       else 
         flash[:error] = "incorrect entries"
         render"new"
        end
      end
   elsif params[:logintype] == "0"
     
      @user = User.new(all_params)
      if @user.save
       sign_in @user
       #redirect_to root_path
    end
      
      #@user = User.new
    #  @user.logintype = params[:logintype]
     # @user.username = params[:username]
    #  @user.email = params[:email]
      
     # @user.password = params[:password]
    #   @user.fbaccesstoken = params[:fbaccesstoken]
     # @user.devicetype =params[:devicetype]
    #  @user.devicetoken =params [:devicetoken]
    #  render json: {'here'=>@user} and return
    # @user.save
     
      # sign_in @user
      # redirect_to root_path
   #  end
   end
     
     
 
  
   # else 
       #flash [:notice] => "please provide correct email and passowrd"
    #  render "new"
  # end  
  end
   private
  def all_params
    params.permit(:logintype,:username,:fbid,:fbaccesstoken,:devicetype,:devicetoken,:email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usermailer_helper.rb
module UsermailerHelper
end

app/views/home/data_input_of_rest_id.html.erb
<h1>gfrgtt</h1>
<%= form_tag(controller: "home", action: "foodcategories" ) do %>
<%= label_tag(:rest_id, "enter restaurant id ") %>
<%= text_field_tag(:rest_id) %><br>

<%= submit_tag("submit")%>
<%end%>

app/views/home/display.html.erb
 
<table>
  <tr>
    <th>List of nearby Restaurants</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @allresults.each do |restaurantlist| %>
  <tr>
    <td><%= restaurantlist.restaurantname %></td>
     <td><%= restaurantlist.address %></td>
      <td><%= restaurantlist.city %></td>
   
    <td class=<%= restaurantlist.id%>> <%= link_to "Show" ,show_foodcategory_path  %></td>
    
  </tr>
<% end %>
</table>
 
<br>

app/views/home/foodcategories.html.erb
 
<table>
  <tr>
    <th>List of cuisines</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @user.each do |foodcategory| %>
  <tr>
    <td><%= foodcategory.foodname %></td>
    <td><%= foodcategory.rest_id %></td>
    
    
     <td> <%= link_to "order",show_fooditem_path %></td>
  </tr>
<% end %>
</table>
 
<br>

app/views/home/fooditems.html.erb
<h1>djhed</h1>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

<h3>Give YOUR location</h3>
<br/>
<br/>

<%= form_tag(controller: "home", action: "display") do %>
    <%= label_tag(:lng, "longitude") %>
    <%= text_field_tag(:lng) %><br>
    <%= label_tag(:lat, "latitude") %>
    <%= text_field_tag(:lat) %><br>



    <%= submit_tag("submit")%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>